<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>IT Skill Education Center | Learn • Practice • Grow</title>
<style>
*{box-sizing:border-box}body{margin:0;font-family:Arial,sans-serif;color:#172033;background:#fff}a{text-decoration:none;color:inherit}.wrap{width:min(1180px,92%);margin:auto}
.top{background:#0d326c;color:#fff;padding:8px 0;font-size:13px}.top .wrap{display:flex;justify-content:space-between;gap:15px;flex-wrap:wrap}
nav{background:#fff;border-bottom:1px solid #e6ebf2;position:sticky;top:0;z-index:9}.nav{height:76px;display:flex;align-items:center;justify-content:space-between;gap:25px}
.brand{display:flex;align-items:center;gap:11px;color:#153b7a;font-weight:800}.brand img{width:48px;height:48px;object-fit:contain;border-radius:50%;border:1px solid #e1e7ef;padding:3px}.brand small{display:block;color:#667085;font-size:11px;margin-top:3px}
.menu{display:flex;gap:24px;align-items:center;font-size:14px;font-weight:700}.menu a:hover{color:#1f5fbd}.btn{display:inline-block;padding:12px 20px;border-radius:9px;font-weight:700}.primary{background:#153b7a;color:#fff}.outline{border:1px solid #cad5e5;color:#153b7a}
.hero{background:linear-gradient(120deg,#edf5ff,#fff 55%,#f4f7fb);padding:78px 0}.hero-grid{display:grid;grid-template-columns:1.15fr .85fr;gap:55px;align-items:center}
.tag{display:inline-block;background:#e6effd;color:#153b7a;padding:7px 12px;border-radius:20px;font-size:12px;font-weight:800}.hero h1{font-size:52px;line-height:1.08;color:#102d5c;margin:18px 0}.hero h1 span{color:#2366c4}.hero p{color:#475467;font-size:17px;line-height:1.7}.actions{display:flex;gap:12px;flex-wrap:wrap;margin-top:25px}
.portal{background:#fff;border:1px solid #e2e8f0;border-radius:22px;padding:28px;box-shadow:0 20px 55px #153b7a1c}.portal h2{color:#153b7a;margin:0 0 6px}.portal>p{font-size:13px;margin:0 0 18px}.mini{display:grid;grid-template-columns:1fr 1fr;gap:12px}.mini div{background:#f5f8fc;border:1px solid #edf1f6;border-radius:13px;padding:17px}.mini b{display:block;color:#153b7a;margin-bottom:4px}.mini span{font-size:12px;color:#667085}
section{padding:75px 0}.head{text-align:center;max-width:700px;margin:0 auto 38px}.head small{color:#2366c4;font-weight:800}.head h2{font-size:34px;color:#102d5c;margin:8px 0}.head p{color:#667085}
.courses{display:grid;grid-template-columns:repeat(3,1fr);gap:20px}.card{border:1px solid #e2e8f0;border-radius:15px;padding:24px;background:#fff}.card:hover{box-shadow:0 12px 32px #153b7a14;transform:translateY(-3px)}.icon{width:48px;height:48px;border-radius:12px;background:#eaf2ff;display:grid;place-items:center;font-size:23px}.card h3{color:#153b7a;margin:15px 0 7px}.card p{color:#667085;font-size:13px;line-height:1.6}
.why{background:#f5f8fc}.why-grid{display:grid;grid-template-columns:1fr 1fr;gap:40px}.blue{background:linear-gradient(135deg,#153b7a,#2366c4);color:#fff;border-radius:20px;padding:35px}.blue h2{font-size:31px}.blue p{opacity:.88;line-height:1.7}.features{display:grid;gap:12px}.feature{background:#fff;border:1px solid #e2e8f0;border-radius:12px;padding:17px}.feature b{color:#153b7a}.feature p{margin:5px 0 0;color:#667085;font-size:13px}
.cta{padding:60px 0}.cta-box{background:#102f65;color:#fff;border-radius:20px;padding:38px;display:flex;justify-content:space-between;align-items:center;gap:20px}.cta-box h2{margin:0 0 6px}.cta-box p{margin:0;opacity:.8}.cta-box .btn{background:#fff;color:#153b7a}
footer{background:#091a31;color:#aebbd0;padding:40px 0 20px}.footer{display:grid;grid-template-columns:2fr 1fr 1fr;gap:35px}footer h3,footer h4{color:#fff}footer p,footer a{font-size:13px;line-height:1.8}.copy{border-top:1px solid #ffffff18;margin-top:30px;padding-top:18px;text-align:center;font-size:12px}
@media(max-width:850px){.menu a:not(.primary){display:none}.hero-grid,.why-grid{grid-template-columns:1fr}.courses{grid-template-columns:1fr 1fr}.hero h1{font-size:42px}}
@media(max-width:580px){.hero{padding:52px 0}.hero h1{font-size:35px}.courses,.mini,.footer{grid-template-columns:1fr}.cta-box{align-items:flex-start;flex-direction:column}.top .wrap{justify-content:center}.brand{font-size:14px}}
</style></head><body>
<div class="top"><div class="wrap"><span>📍 Mandawa, Jhunjhunu, Rajasthan</span><span>Practical Computer Education • Student Exam Portal</span></div></div>
<nav><div class="wrap nav"><a class="brand" href="#"><img src="assets/images/logo.png" alt="Logo"><div>IT Skill Education Center<small>Learn • Practice • Grow</small></div></a><div class="menu"><a href="#home">Home</a><a href="#courses">Courses</a><a href="#why">Why Us</a><a href="#contact">Contact</a><a class="btn primary" href="student/login.php">Student Login</a></div></div></nav>
<header class="hero" id="home"><div class="wrap hero-grid"><div><span class="tag">COMPUTER EDUCATION & PRACTICAL SKILLS</span><h1>Build Skills.<br><span>Build Your Future.</span></h1><p>Learn practical computer skills through structured courses, digital study content, assessments and mock tests at IT Skill Education Center.</p><div class="actions"><a class="btn primary" href="#courses">Explore Courses</a><a class="btn outline" href="student/login.php">Student Portal →</a></div></div>
<div class="portal"><h2>Learn • Practice • Grow</h2><p>A structured digital learning experience for every student.</p><div class="mini"><div><b>📚 E-Content</b><span>Topic-wise study material</span></div><div><b>🎯 Mock Tests</b><span>Practice after lessons</span></div><div><b>📝 Assessments</b><span>Online MCQ examinations</span></div><div><b>📊 Results</b><span>Track performance</span></div></div></div></div></header>
<section id="courses"><div class="wrap"><div class="head"><small>OUR COURSES</small><h2>Learn Skills That Matter</h2><p>Practical courses designed to build useful computer and workplace skills.</p></div><div class="courses">
<div class="card"><div class="icon">💻</div><h3>RS-CIT</h3><p>Essential computer and digital literacy skills for everyday and professional use.</p></div>
<div class="card"><div class="icon">📒</div><h3>Tally Prime Comprehensive</h3><p>Learn accounting workflows and practical business transactions using TallyPrime.</p></div>
<div class="card"><div class="icon">📈</div><h3>Tally Prime Professional</h3><p>Advanced practical accounting and TallyPrime skills for professional work.</p></div>
<div class="card"><div class="icon">🧾</div><h3>GST Simulation</h3><p>Practice GST concepts and workflows through structured learning.</p></div>
<div class="card"><div class="icon">⌨️</div><h3>RCAE</h3><p>Practical computer applications and skill development.</p></div>
<div class="card"><div class="icon">🌐</div><h3>RCWD</h3><p>Develop useful digital and computer skills through guided learning.</p></div>
</div></div></section>
<section class="why" id="why"><div class="wrap why-grid"><div class="blue"><h2>More Than Classroom Learning</h2><p>Students can continue learning through the institute portal with course content, mock tests, assessments, notifications and progress tracking.</p></div><div class="features"><div class="feature"><b>✓ Structured E-Content</b><p>Course → Topic → Lesson based learning.</p></div><div class="feature"><b>✓ Practice & Mock Tests</b><p>Lesson-linked practice tests reinforce concepts.</p></div><div class="feature"><b>✓ Online Assessments</b><p>Complete assigned MCQ exams through the student portal.</p></div><div class="feature"><b>✓ Attendance & Progress</b><p>Keep learning and attendance information organized.</p></div></div></div></section>
<div class="cta" id="contact"><div class="wrap"><div class="cta-box"><div><h2>Ready to Start Learning?</h2><p>Visit IT Skill Education Center, Mandawa for course and admission information.</p></div><a class="btn" href="student/login.php">Open Student Login</a></div></div></div>
<footer><div class="wrap"><div class="footer"><div><h3>IT Skill Education Center</h3><p>Learn • Practice • Grow<br>Practical computer education and digital learning in Mandawa.</p></div><div><h4>Quick Links</h4><p><a href="#courses">Courses</a><br><a href="#why">Why Us</a><br><a href="student/login.php">Student Login</a></p></div><div><h4>Location</h4><p>Mandawa<br>Jhunjhunu, Rajasthan</p></div></div><div class="copy">© 2026 IT Skill Education Center. All rights reserved.</div></div></footer>
</body></html>